pipeline {
	agent any
	stages {
		stage('Checkout') {
			steps {
				git url: 'https://github.com/vishwasraiborde19/platform-cloud.git', credentialsId: '144a2a6e-2625-4e8a-879a-8be974d9ca2b', branch: 'main'
			}
		}

		stage('Build Maven Project') {
			steps {
				dir(path: 'lms-common-model') {
					sh 'mvn clean package'
				}
			}
		}
    }

	post {
		always {
			cleanWs()
		}

		success {
			echo "Pipeline completed successfully!"
		}

	}
}