apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2025-02-19T12:12:29Z","generation":1,"labels":{"app":"platform-event-producer-service","tier":"backend"},"name":"platform-event-producer-service","namespace":"platform","resourceVersion":"9335797","uid":"3e633db0-8427-4f83-bd01-ce0d04788504"},"spec":{"progressDeadlineSeconds":60,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"platform-event-producer-service"}},"strategy":{"rollingUpdate":{"maxSurge":2,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"platform-event-producer-service"}},"spec":{"containers":[{"image":"vishwasraiborde19/platform-event-producer-service-img:latest","imagePullPolicy":"Always","name":"platform-event-producer-service-container","ports":[{"containerPort":7000,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","hostAliases":[{"hostnames":["kafka-node1"],"ip":"192.168.0.87"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":60}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2025-02-19T12:12:33Z","lastUpdateTime":"2025-02-19T12:12:33Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2025-02-19T12:12:29Z","lastUpdateTime":"2025-02-19T12:12:33Z","message":"ReplicaSet \"platform-event-producer-service-77648cb49b\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2025-02-19T15:28:23Z"
  generation: 1
  labels:
    app: platform-event-producer-service
    tier: backend
  name: platform-event-producer-service
  namespace: platform
  resourceVersion: "9378334"
  uid: b11367b7-e8b7-4dad-936b-3c82df62760f
spec:
  progressDeadlineSeconds: 60
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: platform-event-producer-service
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: platform-event-producer-service
    spec:
      containers:
      - image: vishwasraiborde19/platform-event-producer-service-img:latest
        imagePullPolicy: Always
        name: platform-event-producer-service-container
        ports:
        - containerPort: 7000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - kafka-node1
        ip: 192.168.0.87
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-02-19T15:28:26Z"
    lastUpdateTime: "2025-02-19T15:28:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-19T15:28:23Z"
    lastUpdateTime: "2025-02-19T15:28:27Z"
    message: ReplicaSet "platform-event-producer-service-769895c856" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
