server:
  port: 4000

spring:
  application:
    name: platform-rest-mock
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true



