apiVersion: v1
kind: Service
metadata:
  name: lms-user-mgmt-service-svc
  namespace: platform
spec:
  selector:
    app: lms-user-mgmt-service
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
  type: LoadBalancer
  