apiVersion: v1
kind: Service
metadata:
  name: platform-event-producer-service-svc
  namespace: platform
spec:
  selector:
    app: platform-event-producer-service
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: LoadBalancer
  