apiVersion: v1
kind: PersistentVolume
metadata:
  name: co-config-volume
  labels:
    type: co-config-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: kafka
    name: co-config-volume
  hostPath:
    path: " /opt/strimzi/custom-config"