spring:
  application:
    name: platform-web-core
    version: 1.0
  boot:
    admin:
      client:
        url: http://localhost:9000/

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

# for poc purposes only in real , pull properties via service name from eureka instead of context path / urls
com:
  platform:
    api:
      templateMapping:
        user: http://localhost:8080/user
        role: http://localhost:8080/user