spring:
  application:
    name: platform-web-core
    version: 1.0
  boot:
    admin:
      client:
        url: http://localhost:9000/
#actuators
management:
  health:
    ratelimiters:
      enabled: true
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
#service registry
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
# resiliency
#https://github.com/resilience4j/resilience4j-spring-cloud2-demo/blob/master/server/src/main/resources/config/client.yml
#https://refactorfirst.com/spring-cloud-resiliance4j-circuitbreaker-and-retry
resilience4j.bulkhead:
  instances:
    userService:
      max-concurrent-calls: 3
      max-wait-duration: 1
resilience4j.timelimiter:
  instances:
    userService:
      cancel-running-future: true
      timeout-duration: 3s
resilience4j.retry:
  retry-aspect-order: 2
  instances:
    userService:
      base-config: default
  configs:
    default:
      max-attempts: 3
      wait-duration: 3s
resilience4j.circuitbreaker:
  circuit-breaker-aspect-order: 1
  instances:
    userService:
      register-health-indicator: true
      event-consumer-buffer-size: 10
      failure-rate-threshold: 50
      minimum-number-of-calls: 5
      automatic-transition-from-open-to-half-open-enabled: true
      wait-duration-in-open-state: 5s
      permitted-number-of-calls-in-half-open-state: 3
      sliding-window-size: 10
      sliding-window-type: COUNT_BASED

# for poc purposes only in real , pull properties via service name from eureka instead of context path / urls
com:
  platform:
    api:
      templateMapping:
        user: http://localhost:8080/user
        role: http://localhost:8080/user