spring:
  application:
    name: platform-web-core
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

# for poc purposes only in real , pull properties via service name from eureka instead of context path / urls
com:
  platform:
    api:
      templateMapping:
        user: http://localhost:8080/user
        role: http://localhost:8080/user