server:
  port: 9000

spring:
  application:
    name: platform-admin-server


management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true