apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-learning-mgmt-service-cm
  namespace: platform
data:
  spring.application.name: "lms-learning-mgmt-service"
  server.port: "6003"
  spring.datasource.hikari.connection-timeout: "5000"
  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.driver-class-name: "com.mysql.jdbc.Driver"
  spring.datasource.url: "jdbc:mysql://192.168.0.89:3306/lms_plan_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
  spring.datasource.username: "dev"
  spring.jpa.hibernate.ddl-auto: "update"
  # TODO encrypt password with relevant hash
  spring.datasource.password: "dev"
  #spring.jpa.show-sql: true
  logging.level.org.springframework.context: "DEBUG"

  #actuators
  management.endpoints.web.exposure.include: "*"

  #logging
  logging.config: "classpath:spring-log.xml"
  #logging.level.org.springframework.context=DEBUG

  #registry
  eureka.client.enabled: "true"
  eureka.client.fetch-registry: "true"
  eureka.client.register-with-eureka: "true"
  eureka.client.service-url.defaultZone: "http://192.168.0.10:8761/eureka/"
  eureka.instance.preferIpAddress: "true"

