apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: lms-learning-mgmt-pod-dep
    tier: backend
  name: lms-learning-mgmt-pod-dep
  namespace: platform
spec:
  progressDeadlineSeconds: 60
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lms-learning-mgmt-pod-dep
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lms-learning-mgmt-pod-dep
    spec:
      containers:
      - image: vishwasraiborde19/lms-learning-mgmt-service-img:latest
        imagePullPolicy: Always
        name: lms-learning-mgmt-service-container
        envFrom:
          - configMapRef:
              name: lms-learning-mgmt-service-cm
        ports:
        - containerPort: 6003
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        #Liveness probes determine when to restart a container. For example, liveness probes could catch a deadlock when an application is running but unable to make progress.
        #If a container fails its liveness probe repeatedly, the kubelet restarts the container
        livenessProbe:
          httpGet:
            port: 6003
            path: /actuator/health
          initialDelaySeconds: 120 #Number of seconds after the container has started before liveness probes are initiated.
          periodSeconds: 10 #how often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
          failureThreshold: 5 # Minimum consecutive failures for the probe to be considered failed after having succeeded
        readinessProbe:
          httpGet:
            port: 6003
            path: /actuator/health
          timeoutSeconds: 10
          initialDelaySeconds: 120 #Number of seconds after the container has started before liveness probes are initiated.
          periodSeconds: 10 #how often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60

