apiVersion: v1
kind: Service
metadata:
  name: lms-learning-mgmt-service-svc
  namespace: platform
spec:
  selector:
    app: lms-learning-mgmt-pod-dep
  ports:
    - protocol: TCP
      port: 6003
      targetPort: 6003
  type: LoadBalancer
  