apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-admin-server-cm
  namespace: platform
data:
  spring.application.name: "platform-admin-server"
  server.port: "9100"
  #actuators
  management.endpoints.web.exposure.include: "*"
  #registry
  eureka.client.enabled: "false"
  eureka.client.fetch-registry: "false"
  eureka.client.register-with-eureka: "false"
  eureka.client.service-url.defaultZone: "http://192.168.0.8:8761/eureka/"

