apiVersion: v1
kind: Service
metadata:
  name: platform-admin-server-svc
  namespace: platform
spec:
  selector:
    app: platform-admin-server
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
  type: LoadBalancer
  