apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2025-01-27T01:38:20Z","generation":1,"labels":{"app":" platform-web-core","tier":"backend"},"name":" platform-web-core","namespace":"platform","resourceVersion":"3396807","uid":"1a500c5f-3995-4e5a-b93d-feffe1a9be1c"},"spec":{"progressDeadlineSeconds":60,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":" platform-web-core"}},"strategy":{"rollingUpdate":{"maxSurge":2,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":" platform-web-core"}},"spec":{"containers":[{"image":"vishwasraiborde19/platform-web-core_img:1.0","imagePullPolicy":"Always","name":" platform-web-core-container","ports":[{"containerPort":8080,"protocol":"TCP"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":60}}},"status":{"conditions":[{"lastTransitionTime":"2025-01-27T01:38:20Z","lastUpdateTime":"2025-01-27T01:38:20Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2025-01-27T01:39:21Z","lastUpdateTime":"2025-01-27T01:39:21Z","message":"ReplicaSet \" platform-web-core-6bb44cb987\" has timed out progressing.","reason":"ProgressDeadlineExceeded","status":"False","type":"Progressing"}],"observedGeneration":1,"replicas":3,"unavailableReplicas":3,"updatedReplicas":3}}
  creationTimestamp: "2025-01-28T01:13:18Z"
  generation: 1
  labels:
    app:  platform-web-core
    tier: backend
  name: platform-web-core
  namespace: platform
  resourceVersion: "3632646"
  uid: 1c53b643-2b92-45fb-83d8-bda06434c97e
spec:
  progressDeadlineSeconds: 60
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app:  platform-web-core
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app:  platform-web-core
    spec:
      containers:
      - image: vishwasraiborde19/platform-web-core-img:v12
        imagePullPolicy: Always
        name:  platform-web-core-container
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
