apiVersion: v1
kind: Service
metadata:
  name: platform-config-server-svc
  namespace: platform
spec:
  selector:
    app: platform-config-server
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: LoadBalancer
  