apiVersion: v1
kind: Service
metadata:
  name: platform-web-core-svc
  namespace: platform
spec:
  selector:
    app: platform-web-core
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  