apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-eureka-server-cm
  namespace: platform
data:
  spring.application.name: "platform-eureka-server"
  server.port: "8761"
  #actuators
  management.endpoints.web.exposure.include: "*"
  #registry
  eureka.client.register-with-eureka: "false"
  eureka.client.fetch-registry: "false"

  #boot.admin.client.url: "http://192.168.0.11:9100"

  logging.level.com.netflix.eureka: "OFF"
  logging.level.com.netflix.discovery: "OFF"

