apiVersion: v1
kind: Service
metadata:
  name: platform-discovery-server-svc
  namespace: platform
spec:
  selector:
    app: platform-discovery-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
  